//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace leasingAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeasingApplications
    {
        public int IdUser { get; set; }
        public string PhoneNumber { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DataApplications { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
